# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pling-plong-onlinelogin.ui'
#
# Created: Thu Oct  6 01:45:12 2016
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PlingPlongOnlineDialog(object):
    def setupUi(self, PlingPlongOnlineDialog):
        PlingPlongOnlineDialog.setObjectName(_fromUtf8("PlingPlongOnlineDialog"))
        PlingPlongOnlineDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PlingPlongOnlineDialog.resize(601, 448)
        PlingPlongOnlineDialog.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(PlingPlongOnlineDialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox = QtGui.QGroupBox(PlingPlongOnlineDialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.AUXuser = QtGui.QLineEdit(self.groupBox)
        self.AUXuser.setObjectName(_fromUtf8("AUXuser"))
        self.horizontalLayout.addWidget(self.AUXuser)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.AUXpassword = QtGui.QLineEdit(self.groupBox)
        self.AUXpassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.AUXpassword.setObjectName(_fromUtf8("AUXpassword"))
        self.horizontalLayout.addWidget(self.AUXpassword)
        self.AUXlogin = QtGui.QPushButton(self.groupBox)
        self.AUXlogin.setObjectName(_fromUtf8("AUXlogin"))
        self.horizontalLayout.addWidget(self.AUXlogin)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(PlingPlongOnlineDialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.Apollouser = QtGui.QLineEdit(self.groupBox_2)
        self.Apollouser.setObjectName(_fromUtf8("Apollouser"))
        self.horizontalLayout_2.addWidget(self.Apollouser)
        self.label_4 = QtGui.QLabel(self.groupBox_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.Apollopassword = QtGui.QLineEdit(self.groupBox_2)
        self.Apollopassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.Apollopassword.setObjectName(_fromUtf8("Apollopassword"))
        self.horizontalLayout_2.addWidget(self.Apollopassword)
        self.Apollologin = QtGui.QPushButton(self.groupBox_2)
        self.Apollologin.setObjectName(_fromUtf8("Apollologin"))
        self.horizontalLayout_2.addWidget(self.Apollologin)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(PlingPlongOnlineDialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBox_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Universaluser = QtGui.QLineEdit(self.groupBox_3)
        self.Universaluser.setObjectName(_fromUtf8("Universaluser"))
        self.horizontalLayout_3.addWidget(self.Universaluser)
        self.label_6 = QtGui.QLabel(self.groupBox_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_3.addWidget(self.label_6)
        self.Universalpassword = QtGui.QLineEdit(self.groupBox_3)
        self.Universalpassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.Universalpassword.setObjectName(_fromUtf8("Universalpassword"))
        self.horizontalLayout_3.addWidget(self.Universalpassword)
        self.Universallogin = QtGui.QPushButton(self.groupBox_3)
        self.Universallogin.setObjectName(_fromUtf8("Universallogin"))
        self.horizontalLayout_3.addWidget(self.Universallogin)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(PlingPlongOnlineDialog)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_7 = QtGui.QLabel(self.groupBox_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.Uprightuser = QtGui.QLineEdit(self.groupBox_4)
        self.Uprightuser.setObjectName(_fromUtf8("Uprightuser"))
        self.horizontalLayout_4.addWidget(self.Uprightuser)
        self.label_8 = QtGui.QLabel(self.groupBox_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_4.addWidget(self.label_8)
        self.Uprightpassword = QtGui.QLineEdit(self.groupBox_4)
        self.Uprightpassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.Uprightpassword.setObjectName(_fromUtf8("Uprightpassword"))
        self.horizontalLayout_4.addWidget(self.Uprightpassword)
        self.Uprightlogin = QtGui.QPushButton(self.groupBox_4)
        self.Uprightlogin.setObjectName(_fromUtf8("Uprightlogin"))
        self.horizontalLayout_4.addWidget(self.Uprightlogin)
        self.gridLayout.addWidget(self.groupBox_4, 3, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(PlingPlongOnlineDialog)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.groupBox_5)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.Extremeuser = QtGui.QLineEdit(self.groupBox_5)
        self.Extremeuser.setObjectName(_fromUtf8("Extremeuser"))
        self.horizontalLayout_6.addWidget(self.Extremeuser)
        self.label_12 = QtGui.QLabel(self.groupBox_5)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_6.addWidget(self.label_12)
        self.Extremepassword = QtGui.QLineEdit(self.groupBox_5)
        self.Extremepassword.setEchoMode(QtGui.QLineEdit.PasswordEchoOnEdit)
        self.Extremepassword.setObjectName(_fromUtf8("Extremepassword"))
        self.horizontalLayout_6.addWidget(self.Extremepassword)
        self.Extremelogin = QtGui.QPushButton(self.groupBox_5)
        self.Extremelogin.setObjectName(_fromUtf8("Extremelogin"))
        self.horizontalLayout_6.addWidget(self.Extremelogin)
        self.gridLayout.addWidget(self.groupBox_5, 4, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(PlingPlongOnlineDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout.addWidget(self.progressBar, 5, 0, 1, 1)
        self.label.setBuddy(self.AUXuser)
        self.label_2.setBuddy(self.AUXpassword)
        self.label_3.setBuddy(self.AUXuser)
        self.label_4.setBuddy(self.AUXpassword)
        self.label_5.setBuddy(self.AUXuser)
        self.label_6.setBuddy(self.AUXpassword)
        self.label_7.setBuddy(self.AUXuser)
        self.label_8.setBuddy(self.AUXpassword)
        self.label_11.setBuddy(self.AUXuser)
        self.label_12.setBuddy(self.AUXpassword)

        self.retranslateUi(PlingPlongOnlineDialog)
        QtCore.QMetaObject.connectSlotsByName(PlingPlongOnlineDialog)

    def retranslateUi(self, PlingPlongOnlineDialog):
        PlingPlongOnlineDialog.setWindowTitle(_translate("PlingPlongOnlineDialog", "Online services for metadata lookup", None))
        PlingPlongOnlineDialog.setToolTip(_translate("PlingPlongOnlineDialog", "Add your credentials to online services", None))
        self.groupBox.setTitle(_translate("PlingPlongOnlineDialog", "AUX (auxmp.com)", None))
        self.label.setText(_translate("PlingPlongOnlineDialog", "Username:", None))
        self.label_2.setText(_translate("PlingPlongOnlineDialog", "Password:", None))
        self.AUXlogin.setText(_translate("PlingPlongOnlineDialog", "Login", None))
        self.groupBox_2.setTitle(_translate("PlingPlongOnlineDialog", "Apollo Music (findthetune.com)", None))
        self.label_3.setText(_translate("PlingPlongOnlineDialog", "Username:", None))
        self.label_4.setText(_translate("PlingPlongOnlineDialog", "Password:", None))
        self.Apollologin.setText(_translate("PlingPlongOnlineDialog", "Login", None))
        self.groupBox_3.setTitle(_translate("PlingPlongOnlineDialog", "Universal Publishing Production Music (unippm.se)", None))
        self.label_5.setText(_translate("PlingPlongOnlineDialog", "Username:", None))
        self.label_6.setText(_translate("PlingPlongOnlineDialog", "Password:", None))
        self.Universallogin.setText(_translate("PlingPlongOnlineDialog", "Login", None))
        self.groupBox_4.setTitle(_translate("PlingPlongOnlineDialog", "Upright Music (upright-music.com)", None))
        self.label_7.setText(_translate("PlingPlongOnlineDialog", "Username:", None))
        self.label_8.setText(_translate("PlingPlongOnlineDialog", "Password:", None))
        self.Uprightlogin.setText(_translate("PlingPlongOnlineDialog", "Login", None))
        self.groupBox_5.setTitle(_translate("PlingPlongOnlineDialog", "Extreme Music (extrememusic.com)", None))
        self.label_11.setText(_translate("PlingPlongOnlineDialog", "Username:", None))
        self.label_12.setText(_translate("PlingPlongOnlineDialog", "Password:", None))
        self.Extremelogin.setText(_translate("PlingPlongOnlineDialog", "Login", None))

