sudo: true
# we dont want to use the container based setup because fuse isnt available there, so we set "sudo: true"

language: python

matrix:
  include:
    #- os: linux
    #  dist: trusty
    #  sudo: required
    #  python: 2.7

    - os: osx
      osx_image: xcode7.2
      language: generic

# dont test feature branches
branches:
  only:
    - master

# install dependencies
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update || brew update; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install python; fi
  - pip install py2app

# install our program
install:
  - pip install -r requirements.txt
  - pip install .
  - ls

script:
  # run tests
  #- PYTHONPATH=$PYTHONPATH:./src py.test tests/
  # create package
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then ./build-mac.sh; fi
