# https://ci.appveyor.com/project/havardgulldahl/odometer
build: false

environment:
  matrix:
    #- PYTHON: "C:/Python27/python.exe" # this is win32
      #PPATH: "C:/Python27"
      #LXML: "test/contrib/lxml-3.6.4-cp27-cp27m-win32.whl"
      #PY2EXE: "py2exe_py2"
      #PYQT: "https://www.dropbox.com/s/vrzlipbjocuiofb/PyQt4-4.11.4-cp27-none-win32.whl?dl=1"
      #MSVCP: "https://www.dropbox.com/s/57tqa3oiqqf7s4j/msvcp90.dll?dl=1"
      #REQUIREMENTS: "requirements.txt"
      #PIP: "%PPATH%/Scripts/pip.exe"
    - PYTHON: "C:/Python34/python.exe"
      PPATH: "C:/Python34"
      #LXML: "lxml"
      LXML: "https://www.dropbox.com/s/0set0he3faci14e/lxml-3.7.2-cp34-cp34m-win32.whl?dl=1"
      PY2EXE: "py2exe"
      PYQT: "PyQt5"
      REQUIREMENTS: "requirements.txt"
      PIP: "%PPATH%/Scripts/pip.exe"
      MSVCP: "https://www.dropbox.com/s/57tqa3oiqqf7s4j/msvcp90.dll?dl=1"
    #- PYTHON: "C:\\Python27-x64" #TODO: enable x64 build
    #  PYTHON_VERSION: "2.7.x" # currently 2.7.9
    #  PYTHON_ARCH: "64"
init:
  - "ECHO %PYTHON%"
  - "SET PYTHONPATH=%PYTHONPATH%;tests;%CD%\\tests"
  - "SET PATH=%PPATH%;%PPATH%\\Scripts;%PATH%"
  #- ps: Invoke-WebRequest "https://bootstrap.pypa.io/ez_setup.py" -OutFile "c:/ez_setup.py"
  #- ps: Invoke-WebRequest "https://bootstrap.pypa.io/get-pip.py" -OutFile "c:/get-pip.py"
  - ps: "git config --global core.autocrlf false" # always use unix lineendings


install:
  #- "%PYTHON% c:/ez_setup.py > NUL"
  #- "%PYTHON% c:/get-pip.py"
  - "%PIP% install %LXML%"
  - "%PIP% install %PY2EXE%"
  - "%PIP% install %PYQT%"
  - "%PIP% install -r %REQUIREMENTS%"
  - "%PIP% install ."
  - ps: Invoke-WebRequest "$env:MSVCP" -OutFile "C:\projects\pling-plong-odometer\MSVCP90.dll"

build_script:
  - echo Building..
  #- build-win.sh
  - "%PYTHON% buildpyqt.py"
  - "%PYTHON% setup.py py2exe"
  - "%PYTHON% dist.py zip"
  - dir dist\

#test_script:
  #- echo "PYTHONPATH=%PYTHONPATH%"
  # TODO: enable test scipts
  #- "%PYTHON%/Scripts/py.test test.py"

artifacts:
  - path: odometer-*\odometer*.zip
    name: Odometer Zip

#deploy:
#  provider: Environment
#  name: GitHub
#  on:
#    branch: master
#    appveyor_repo_tag: true

#deploy:
#  provider: S3
#  access_key_id: AKIAJTPGNIAI5CIPIANA
#  secret_access_key:
#  bucket: pling-plong-odometer
#  region: eu-west-1
#  set_public: false
#  folder: win32
#  artifact: odometer-*\odometer*.zip
